[global]
developmentMode = false

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 10
maxMessageSize = 200

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#667eea"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#333333"
font = "sans serif"

[client]
caching = true
displayEnabled = true
showErrorDetails = false
